---
title: "exercise11"
author: "Sabrina Garcia"
date: "May 18, 2018"
output: html_document
---

```{r packages}
  library(leaflet)
  library(dplyr)
  library(tidyr)
  library(ggplot2)
  library(DT)
```


```{r data}
esc <- read.csv("data/escapement_counts.csv", stringsAsFactors = FALSE)
```

```{r median_calc}
median_esc <- esc %>% 
  separate(sampleDate, c("Month", "Day", "Year"), sep = "/") %>% 
  group_by(Species, SASAP.Region, Year, Location) %>% 
  summarize(escapement = sum(DailyCount)) %>% 
  group_by(Species) %>% 
  summarize(median_escapement = median(escapement))
```

```{r ggplot_flipped_column}
ggplot(median_esc, aes(Species, median_escapement)) +
  geom_col() +
  coord_flip()
```

```{r locations}
locations <- esc %>% 
  distinct(Location, Latitude, Longitude) %>% 
  drop_na()
```

```{r dt}
datatable(locations)
```

```{r marker}
markerIcon <- makeIcon(
  iconUrl = "https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.3.1/images/marker-icon.png",
  iconWidth = 25, iconHeight = 41,
  iconAnchorX = 12, iconAnchorY = 41,
  shadowUrl = "https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.3.1/images/marker-shadow.png",
  shadowWidth = 41, shadowHeight = 41,
  shadowAnchorX = 13, shadowAnchorY = 41
)
```

```{r correct_longs}
locs <- locations %>% mutate( Longitude = abs(Longitude) * -1 )
```

```{r map}
leaflet(locs) %>% 
  addTiles() %>% 
  addMarkers(~ Longitude, ~ Latitude, popup = ~ Location, icon=markerIcon )
```




